name: noro
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bedtools=2.30.0=h0e31d98_3
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py311h5547dcb_1005
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2022.9.24=h033912b_0
  - cairo=1.16.0=h904041c_1014
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.15.1=py311ha86e640_2
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py311h6eed73b_1
  - coloredlogs=15.0.1=pyhd8ed1ab_3
  - colormath=3.0.0=py_2
  - commonmark=0.9.1=py_0
  - contourpy=1.0.6=py311hd2070f0_0
  - cryptography=38.0.4=py311h8661239_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - expat=2.5.0=hf0c8a7f_0
  - fastp=0.23.2=h15641a5_3
  - fastqc=0.11.9=hdfd78af_1
  - fastx_toolkit=0.0.14=hb19a6fa_10
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py311h5547dcb_1
  - freetype=2.12.1=h3f81eb7_1
  - fribidi=1.0.10=hbcb3906_0
  - future=0.18.2=pyhd8ed1ab_6
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=hbcb3906_2
  - glib=2.74.1=hbc0c0cd_1
  - glib-tools=2.74.1=hbc0c0cd_1
  - gnuplot=5.4.5=h62d52a3_0
  - graphite2=1.3.13=h2e338ed_1001
  - gst-plugins-base=1.21.2=h37e1711_0
  - gstreamer=1.21.2=h1d18e73_0
  - harfbuzz=5.3.0=h08f8713_0
  - humanfriendly=10.0=py311h6eed73b_4
  - icu=70.1=h96cf925_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=5.1.0=pyha770c72_0
  - isa-l=2.30.0=h0d85af4_4
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=hac89ed1_2
  - kiwisolver=1.4.4=py311hd2070f0_1
  - krb5=1.19.3=hb49756b_0
  - lcms2=2.14=h90f4b2a_0
  - lerc=4.0.0=hb486fe8_0
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libclang=15.0.5=default_h20dc2f0_0
  - libclang13=15.0.5=default_hc4b5f92_0
  - libcxx=14.0.6=hccf4f1f_0
  - libdeflate=1.13=h775f41a_0
  - libedit=3.1.20191231=h0678c8f_2
  - libffi=3.4.2=h0d85af4_5
  - libgd=2.3.3=h1e214de_3
  - libgfortran=5.0.0=9_5_0_h97931a8_26
  - libgfortran5=11.3.0=h082f757_26
  - libglib=2.74.1=h4c723e1_1
  - libgtextutils=0.7=h9722bc1_9
  - libiconv=1.17=hac89ed1_0
  - liblapack=3.9.0=16_osx64_openblas
  - libllvm15=15.0.5=h7001e86_0
  - libogg=1.3.4=h35c211d_1
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.39=ha978bb4_0
  - libpq=14.5=h50fae06_1
  - libsqlite=3.40.0=ha978bb4_0
  - libtiff=4.4.0=h5e0c7b4_3
  - libvorbis=1.3.7=h046ec9c_0
  - libwebp=1.2.4=hfa4350a_0
  - libwebp-base=1.2.4=h775f41a_0
  - libxcb=1.13=h0d85af4_1004
  - libxml2=2.10.3=hb9e07b5_0
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=15.0.5=h61d9ccf_0
  - lzstring=1.0.4=py_1001
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py311h5547dcb_2
  - matplotlib-base=3.6.2=py311h2bf763f_0
  - multiqc=1.13=pyhdfd78af_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.31=h7ebae80_0
  - mysql-libs=8.0.31=hc37e033_0
  - ncurses=6.3=h96cf925_1
  - networkx=2.8.8=pyhd8ed1ab_0
  - nspr=4.32=hcd9eead_1
  - nss=3.78=ha8197d3_0
  - numpy=1.23.5=py311h62c7003_0
  - openjdk=17.0.3=hbc0c0cd_4
  - openjpeg=2.5.0=h5d0d7b0_1
  - openssl=1.1.1s=hfd90126_0
  - packaging=21.3=pyhd8ed1ab_0
  - pango=1.50.12=h7fca291_0
  - pcre2=10.40=h1c4e4bc_0
  - perl=5.32.1=2_h0d85af4_perl5
  - perl-gd=2.76=pl5321hb8176d5_1
  - perl-gdgraph=1.54=pl5321hdfd78af_1
  - perl-gdgraph-histogram=1.1=pl5321hdfd78af_4
  - perl-gdtextutil=0.86=pl5321ha5712d3_7
  - perl-perlio-gzip=0.20=pl5321h1f540d2_3
  - pillow=9.2.0=py311he7df5c9_3
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - pthread-stubs=0.4=hc929b4f_1001
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.0=ha621ccb_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pyyaml=6.0=py311h5547dcb_5
  - qt-main=5.15.6=he0d2461_2
  - readline=8.1.2=h3899abd_0
  - requests=2.28.1=pyhd8ed1ab_1
  - rich=12.6.0=pyhd8ed1ab_0
  - rich-click=1.5.2=pyhd8ed1ab_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - simplejson=3.18.0=py311h5547dcb_0
  - six=1.16.0=pyh6c4a22f_0
  - spectra=0.0.11=py_1
  - sqlite=3.40.0=h9ae0607_0
  - tk=8.6.12=h5dbffcc_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022f=h191b570_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfd90126_4
  - zstd=1.5.2=hfa58983_4
prefix: /opt/miniconda/envs/noro
